In [10]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
import os
os.getcwd()

'C:\\Users\\inbar\\OneDrive - Ariel University\\my_notebook\\tirgulim'

In [4]:
path = 'Iowa Liquor Sales (Jan 2021-Jan 2022).csv'
pd.read_csv(path)

,invoice_and_item_number,date,store_number,store_name,address,city,zip_code,store_location,county_number,county,...,item_number,item_description,pack,bottle_volume_ml,state_bottle_cost,state_bottle_retail,bottles_sold,sale_dollars,volume_sold_liters,volume_sold_gallons
0,INV-33179700135,2021-01-04,2576,Hy-Vee Wine and Spirits / Storm Lake,1250 N Lake St,Storm Lake,50588.0,POINT (-95.200758 42.65318400000001),11.0,BUENA VIST,...,64870,Fireball Cinnamon Whiskey,48,100,0.90,1.35,48,64.80,4.80,1.26
1,INV-33196200106,2021-01-04,2649,Hy-Vee #3 / Dubuque,400 Locust St,Dubuque,52001.0,POINT (-90.666497 42.49721900000001),31.0,DUBUQUE,...,65200,Tequila Rose Liqueur,12,750,11.50,17.25,4,69.00,3.00,0.79
2,INV-33184300011,2021-01-04,2539,Hy-Vee Food Store / Iowa Falls,640 S. Oak,Iowa Falls,50126.0,POINT (-93.262364 42.508752),42.0,HARDIN,...,38008,Smirnoff 80prf PET,6,1750,14.75,22.13,6,132.78,10.50,2.77
3,INV-33184100015,2021-01-04,4024,Wal-Mart 1546 / Iowa Falls,840 S Oak,Iowa Falls,50126.0,POINT (-93.262446 42.503407),42.0,HARDIN,...,36648,Caliber Vodka,12,750,3.31,4.97,12,59.64,9.00,2.37
4,INV-33174200025,2021-01-04,5385,Vine Food & Liquor,2704 Vine St.,West Des Moines,50265.0,POINT (-93.741511 41.580206),77.0,POLK,...,4626,Buchanan Deluxe 12YR,12,750,20.99,31.49,2,62.98,1.50,0.39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2805302,INV-41968600007,2021-11-14,4617,Lickety Liquor,2501 HUBBELL AVE,Des Moines,50317.0,POINT (-93.570489 41.607817),77.0,POLK,...,87937,Juarez Silver,12,1000,7.83,11.75,1,11.75,1.00,0.26
2805303,INV-41968600008,2021-11-14,4617,Lickety Liquor,2501 HUBBELL AVE,Des Moines,50317.0,POINT (-93.570489 41.607817),77.0,POLK,...,89387,Juarez Gold,12,1000,7.83,11.75,1,11.75,1.00,0.26
2805304,INV-41968600009,2021-11-14,4617,Lickety Liquor,2501 HUBBELL AVE,Des Moines,50317.0,POINT (-93.570489 41.607817),77.0,POLK,...,39492,New Amsterdam Pink Whitney,12,750,7.50,11.25,3,33.75,2.25,0.59
2805305,INV-41968600006,2021-11-14,4617,Lickety Liquor,2501 HUBBELL AVE,Des Moines,50317.0,POINT (-93.570489 41.607817),77.0,POLK,...,89836,Hornitos Reposado,12,750,13.50,20.25,2,40.50,1.50,0.39
2805306,INV-41968600005,2021-11-14,4617,Lickety Liquor,2501 HUBBELL AVE,Des Moines,50317.0,POINT (-93.570489 41.607817),77.0,POLK,...,87646,Exotico Blanco,12,750,11.00,16.50,1,16.50,0.75,0.19

In [5]:
# קריאת הקובץ המקורי
large_csv_file = 'Iowa Liquor Sales (Jan 2021-Jan 2022).csv'

chunk_size = 100000  # גודל חלק רצוי
# 89184 rows × 83 columns

# קריאת הקובץ בגודלי חלקים ושמירתם כקבצים נפרדים
for i, chunk in enumerate(pd.read_csv(large_csv_file, chunksize=chunk_size)):
    chunk.to_csv(f'C:\\Users\\inbar\OneDrive - Ariel University\\my_notebook\\tirgulim\\big_data\\Iowa Liquor Sales (Jan 2021-Jan 2022){i}.csv', index=False)

In [6]:
# DataFrame ריק כדי לאחסן את כל הדאטה
csv_files = ['https://raw.githubusercontent.com/inbarK22/project/main/Iowa%20Liquor%20Sales%20(Jan%202021-Jan%202022)0.csv', 'https://raw.githubusercontent.com/inbarK22/project/main/Iowa%20Liquor%20Sales%20(Jan%202021-Jan%202022)1.csv' , 'https://raw.githubusercontent.com/inbarK22/project/main/Iowa%20Liquor%20Sales%20(Jan%202021-Jan%202022)2.csv' , 'https://raw.githubusercontent.com/inbarK22/project/main/Iowa%20Liquor%20Sales%20(Jan%202021-Jan%202022)3.csv' , 'https://raw.githubusercontent.com/inbarK22/project/main/Iowa%20Liquor%20Sales%20(Jan%202021-Jan%202022)4.csv' , 'https://raw.githubusercontent.com/inbarK22/project/main/Iowa%20Liquor%20Sales%20(Jan%202021-Jan%202022)5.csv' , 'https://raw.githubusercontent.com/inbarK22/project/main/Iowa%20Liquor%20Sales%20(Jan%202021-Jan%202022)6.csv' , 'https://raw.githubusercontent.com/inbarK22/project/main/Iowa%20Liquor%20Sales%20(Jan%202021-Jan%202022)7.csv' , 'https://raw.githubusercontent.com/inbarK22/project/main/Iowa%20Liquor%20Sales%20(Jan%202021-Jan%202022)8.csv' , 'https://raw.githubusercontent.com/inbarK22/project/main/Iowa%20Liquor%20Sales%20(Jan%202021-Jan%202022)9.csv' , 'https://raw.githubusercontent.com/inbarK22/project/main/Iowa%20Liquor%20Sales%20(Jan%202021-Jan%202022)10.csv' , 'https://raw.githubusercontent.com/inbarK22/project/main/Iowa%20Liquor%20Sales%20(Jan%202021-Jan%202022)11.csv' , 'https://raw.githubusercontent.com/inbarK22/project/main/Iowa%20Liquor%20Sales%20(Jan%202021-Jan%202022)12.csv' , 'https://raw.githubusercontent.com/inbarK22/project/main/Iowa%20Liquor%20Sales%20(Jan%202021-Jan%202022)13.csv' , 'https://raw.githubusercontent.com/inbarK22/project/main/Iowa%20Liquor%20Sales%20(Jan%202021-Jan%202022)14.csv' , 'https://raw.githubusercontent.com/inbarK22/project/main/Iowa%20Liquor%20Sales%20(Jan%202021-Jan%202022)15.csv' , 'https://raw.githubusercontent.com/inbarK22/project/main/Iowa%20Liquor%20Sales%20(Jan%202021-Jan%202022)16.csv' , 'https://raw.githubusercontent.com/inbarK22/project/main/Iowa%20Liquor%20Sales%20(Jan%202021-Jan%202022)17.csv' , 'https://raw.githubusercontent.com/inbarK22/project/main/Iowa%20Liquor%20Sales%20(Jan%202021-Jan%202022)18.csv' , 'https://raw.githubusercontent.com/inbarK22/project/main/Iowa%20Liquor%20Sales%20(Jan%202021-Jan%202022)19.csv' , 'https://raw.githubusercontent.com/inbarK22/project/main/Iowa%20Liquor%20Sales%20(Jan%202021-Jan%202022)20.csv' , 'https://raw.githubusercontent.com/inbarK22/project/main/Iowa%20Liquor%20Sales%20(Jan%202021-Jan%202022)21.csv' , 'https://raw.githubusercontent.com/inbarK22/project/main/Iowa%20Liquor%20Sales%20(Jan%202021-Jan%202022)22.csv' , 'https://raw.githubusercontent.com/inbarK22/project/main/Iowa%20Liquor%20Sales%20(Jan%202021-Jan%202022)23.csv' , 'https://raw.githubusercontent.com/inbarK22/project/main/Iowa%20Liquor%20Sales%20(Jan%202021-Jan%202022)24.csv' , 'https://raw.githubusercontent.com/inbarK22/project/main/Iowa%20Liquor%20Sales%20(Jan%202021-Jan%202022)25.csv' , 'https://raw.githubusercontent.com/inbarK22/project/main/Iowa%20Liquor%20Sales%20(Jan%202021-Jan%202022)26.csv' , 'https://raw.githubusercontent.com/inbarK22/project/main/Iowa%20Liquor%20Sales%20(Jan%202021-Jan%202022)27.csv' , 'https://raw.githubusercontent.com/inbarK22/project/main/Iowa%20Liquor%20Sales%20(Jan%202021-Jan%202022)28.csv' ]

merged_df = pd.DataFrame()

# עבור כל קישור, קרא את הקובץ CSV והוסף את הדאטה ל-DataFrame הראשי
for link in csv_files:
    df = pd.read_csv(link)
    merged_df = pd.concat([merged_df, df], ignore_index=True)

In [7]:
merged_df

,invoice_and_item_number,date,store_number,store_name,address,city,zip_code,store_location,county_number,county,...,item_number,item_description,pack,bottle_volume_ml,state_bottle_cost,state_bottle_retail,bottles_sold,sale_dollars,volume_sold_liters,volume_sold_gallons
0,INV-33179700135,2021-01-04,2576,Hy-Vee Wine and Spirits / Storm Lake,1250 N Lake St,Storm Lake,50588.0,POINT (-95.200758 42.65318400000001),11.0,BUENA VIST,...,64870,Fireball Cinnamon Whiskey,48,100,0.90,1.35,48,64.80,4.80,1.26
1,INV-33196200106,2021-01-04,2649,Hy-Vee #3 / Dubuque,400 Locust St,Dubuque,52001.0,POINT (-90.666497 42.49721900000001),31.0,DUBUQUE,...,65200,Tequila Rose Liqueur,12,750,11.50,17.25,4,69.00,3.00,0.79
2,INV-33184300011,2021-01-04,2539,Hy-Vee Food Store / Iowa Falls,640 S. Oak,Iowa Falls,50126.0,POINT (-93.262364 42.508752),42.0,HARDIN,...,38008,Smirnoff 80prf PET,6,1750,14.75,22.13,6,132.78,10.50,2.77
3,INV-33184100015,2021-01-04,4024,Wal-Mart 1546 / Iowa Falls,840 S Oak,Iowa Falls,50126.0,POINT (-93.262446 42.503407),42.0,HARDIN,...,36648,Caliber Vodka,12,750,3.31,4.97,12,59.64,9.00,2.37
4,INV-33174200025,2021-01-04,5385,Vine Food & Liquor,2704 Vine St.,West Des Moines,50265.0,POINT (-93.741511 41.580206),77.0,POLK,...,4626,Buchanan Deluxe 12YR,12,750,20.99,31.49,2,62.98,1.50,0.39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2805302,INV-41968600007,2021-11-14,4617,Lickety Liquor,2501 HUBBELL AVE,Des Moines,50317.0,POINT (-93.570489 41.607817),77.0,POLK,...,87937,Juarez Silver,12,1000,7.83,11.75,1,11.75,1.00,0.26
2805303,INV-41968600008,2021-11-14,4617,Lickety Liquor,2501 HUBBELL AVE,Des Moines,50317.0,POINT (-93.570489 41.607817),77.0,POLK,...,89387,Juarez Gold,12,1000,7.83,11.75,1,11.75,1.00,0.26
2805304,INV-41968600009,2021-11-14,4617,Lickety Liquor,2501 HUBBELL AVE,Des Moines,50317.0,POINT (-93.570489 41.607817),77.0,POLK,...,39492,New Amsterdam Pink Whitney,12,750,7.50,11.25,3,33.75,2.25,0.59
2805305,INV-41968600006,2021-11-14,4617,Lickety Liquor,2501 HUBBELL AVE,Des Moines,50317.0,POINT (-93.570489 41.607817),77.0,POLK,...,89836,Hornitos Reposado,12,750,13.50,20.25,2,40.50,1.50,0.39
2805306,INV-41968600005,2021-11-14,4617,Lickety Liquor,2501 HUBBELL AVE,Des Moines,50317.0,POINT (-93.570489 41.607817),77.0,POLK,...,87646,Exotico Blanco,12,750,11.00,16.50,1,16.50,0.75,0.19

In [9]:
path = 'Iowa Liquor Sales (Jan 2021-Jan 2022).csv'
pd.read_csv(path)

,invoice_and_item_number,date,store_number,store_name,address,city,zip_code,store_location,county_number,county,...,item_number,item_description,pack,bottle_volume_ml,state_bottle_cost,state_bottle_retail,bottles_sold,sale_dollars,volume_sold_liters,volume_sold_gallons
0,INV-33179700135,2021-01-04,2576,Hy-Vee Wine and Spirits / Storm Lake,1250 N Lake St,Storm Lake,50588.0,POINT (-95.200758 42.65318400000001),11.0,BUENA VIST,...,64870,Fireball Cinnamon Whiskey,48,100,0.90,1.35,48,64.80,4.80,1.26
1,INV-33196200106,2021-01-04,2649,Hy-Vee #3 / Dubuque,400 Locust St,Dubuque,52001.0,POINT (-90.666497 42.49721900000001),31.0,DUBUQUE,...,65200,Tequila Rose Liqueur,12,750,11.50,17.25,4,69.00,3.00,0.79
2,INV-33184300011,2021-01-04,2539,Hy-Vee Food Store / Iowa Falls,640 S. Oak,Iowa Falls,50126.0,POINT (-93.262364 42.508752),42.0,HARDIN,...,38008,Smirnoff 80prf PET,6,1750,14.75,22.13,6,132.78,10.50,2.77
3,INV-33184100015,2021-01-04,4024,Wal-Mart 1546 / Iowa Falls,840 S Oak,Iowa Falls,50126.0,POINT (-93.262446 42.503407),42.0,HARDIN,...,36648,Caliber Vodka,12,750,3.31,4.97,12,59.64,9.00,2.37
4,INV-33174200025,2021-01-04,5385,Vine Food & Liquor,2704 Vine St.,West Des Moines,50265.0,POINT (-93.741511 41.580206),77.0,POLK,...,4626,Buchanan Deluxe 12YR,12,750,20.99,31.49,2,62.98,1.50,0.39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2805302,INV-41968600007,2021-11-14,4617,Lickety Liquor,2501 HUBBELL AVE,Des Moines,50317.0,POINT (-93.570489 41.607817),77.0,POLK,...,87937,Juarez Silver,12,1000,7.83,11.75,1,11.75,1.00,0.26
2805303,INV-41968600008,2021-11-14,4617,Lickety Liquor,2501 HUBBELL AVE,Des Moines,50317.0,POINT (-93.570489 41.607817),77.0,POLK,...,89387,Juarez Gold,12,1000,7.83,11.75,1,11.75,1.00,0.26
2805304,INV-41968600009,2021-11-14,4617,Lickety Liquor,2501 HUBBELL AVE,Des Moines,50317.0,POINT (-93.570489 41.607817),77.0,POLK,...,39492,New Amsterdam Pink Whitney,12,750,7.50,11.25,3,33.75,2.25,0.59
2805305,INV-41968600006,2021-11-14,4617,Lickety Liquor,2501 HUBBELL AVE,Des Moines,50317.0,POINT (-93.570489 41.607817),77.0,POLK,...,89836,Hornitos Reposado,12,750,13.50,20.25,2,40.50,1.50,0.39
2805306,INV-41968600005,2021-11-14,4617,Lickety Liquor,2501 HUBBELL AVE,Des Moines,50317.0,POINT (-93.570489 41.607817),77.0,POLK,...,87646,Exotico Blanco,12,750,11.00,16.50,1,16.50,0.75,0.19

In [12]:
print(merged_df.head())
print(merged_df.info())

  invoice_and_item_number        date  store_number  \
0         INV-33179700135  2021-01-04          2576
1         INV-33196200106  2021-01-04          2649
2         INV-33184300011  2021-01-04          2539
3         INV-33184100015  2021-01-04          4024
4         INV-33174200025  2021-01-04          5385

                             store_name         address             city  \
0  Hy-Vee Wine and Spirits / Storm Lake  1250 N Lake St       Storm Lake
1                   Hy-Vee #3 / Dubuque   400 Locust St          Dubuque
2        Hy-Vee Food Store / Iowa Falls      640 S. Oak       Iowa Falls
3            Wal-Mart 1546 / Iowa Falls       840 S Oak       Iowa Falls
4                    Vine Food & Liquor   2704 Vine St.  West Des Moines

   zip_code                        store_location  county_number      county  \
0   50588.0  POINT (-95.200758 42.65318400000001)           11.0  BUENA VIST
1   52001.0  POINT (-90.666497 42.49721900000001)           31.0     DUBUQUE
2   50126.0          POINT (-93.262364 42.508752)           42.0      HARDIN
3   50126.0          POINT (-93.262446 42.503407)           42.0      HARDIN
4   50265.0          POINT (-93.741511 41.580206)           77.0        POLK

   ...  item_number           item_description  pack bottle_volume_ml  \
0  ...        64870  Fireball Cinnamon Whiskey    48              100
1  ...        65200       Tequila Rose Liqueur    12              750
2  ...        38008         Smirnoff 80prf PET     6             1750
3  ...        36648              Caliber Vodka    12              750
4  ...         4626       Buchanan Deluxe 12YR    12              750

   state_bottle_cost state_bottle_retail  bottles_sold  sale_dollars  \
0               0.90                1.35            48         64.80
1              11.50               17.25             4         69.00
2              14.75               22.13             6        132.78
3               3.31                4.97            12         59.64
4              20.99               31.49             2         62.98

   volume_sold_liters  volume_sold_gallons
0                 4.8                 1.26
1                 3.0                 0.79
2                10.5                 2.77
3                 9.0                 2.37
4                 1.5                 0.39

[5 rows x 24 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2805307 entries, 0 to 2805306
Data columns (total 24 columns):
 #   Column                   Dtype
---  ------                   -----
 0   invoice_and_item_number  object
 1   date                     object
 2   store_number             int64
 3   store_name               object
 4   address                  object
 5   city                     object
 6   zip_code                 float64
 7   store_location           object
 8   county_number            float64
 9   county                   object
 10  category                 float64
 11  category_name            object
 12  vendor_number            float64
 13  vendor_name              object
 14  item_number              int64
 15  item_description         object
 16  pack                     int64
 17  bottle_volume_ml         int64
 18  state_bottle_cost        float64
 19  state_bottle_retail      float64
 20  bottles_sold             int64
 21  sale_dollars             float64
 22  volume_sold_liters       float64
 23  volume_sold_gallons      float64
dtypes: float64(9), int64(5), object(10)
memory usage: 513.7+ MB
None